name: Merge

on:
  push:
    branches:
      - main

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      ver: ${{ steps.vars.outputs.ver }}
    steps:
      - name: Use repository
        uses: actions/checkout@v2
      - name: Build variables
        id: vars
        run: |
          echo "::set-output name=ver::$(git rev-parse --short "$GITHUB_SHA")"
      - name: Upload repository
        uses: actions/upload-artifact@v2
        with:
          name: repository
          path: ${{ github.workspace }}

  build-dev:
    needs: setup
    name: '📌Build branch develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  test-main:
    needs: 'build-dev'
    name: '🚀Test main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Test Main
        run: mvn test --file pom.xml

  docker:
    needs: [setup, build-dev, test-main]
    name: '🚀Docker Hub'
    runs-on: ubuntu-latest
    steps:
      - name: Download repository
        uses: actions/download-artifact@v2
        with:
          name: repository
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: ${{ github.repository }}:latest
          build-args: VER=${{ needs.setup.outputs.ver }}