name: Merge

on:
  push:
    branches:
      - main

jobs:

  test:
    name: '🚀Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Test Main
        run: mvn test --file pom.xml

  build:
    needs: 'test'
    name: '🚀 Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - name: upload jar
        run : mkdir -p backend/target && cp target/*.jar backend/target/ && cp Dockerfile backend/
      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: backend
          retention-days: 1

  docker:
    needs: [ test, build ]
    name: '🚀Docker Hub'
    runs-on: ubuntu-latest
    steps:
      - id: sets-a-secret
        name: Generate, mask, and output a secret
        run: |
            the_secret=$((RANDOM))
            echo "secret-number=$the_secret" >> "$GITHUB_OUTPUT"
 #       run: TAG=$(echo ${GITHUB_SHA::8}) >> $env:GITHUB_ENV
  #    - name: Update deployment file
 #       run: TAG=$(echo ${GITHUB_SHA::8})
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Download repository
        uses: actions/download-artifact@v3
        with:
          name: artifact
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          file: Dockerfile
          tags: ${{ secrets.DOCKERHUB_USER }}/backend:${{ steps.sets-a-secret.outputs.secret-number }}