name: Merge

on:
  push:
    branches:
      - main

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Use repository
        uses: actions/checkout@v3
      - name: Build variables
        id: vars
        run: |
          echo "$GITHUB_SHA"

  test:
    needs: 'setup'
    name: '🚀Test main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Test Main
        run: mvn test --file pom.xml

  build:
    needs: 'test'
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir target && cp target/*.jar target
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: target

  docker:
    needs: [setup, test, build]
    name: '🚀Docker Hub'
    runs-on: ubuntu-latest
    steps:
      - name: Download repository
        uses: actions/download-artifact@v2
        with:
          name: repository
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: ${{ github.repository }}:latest
          build-args: VER=${{ needs.setup.outputs.ver }}